/**
 * 
 */
package com.github.downgoon.jresty.rest.auto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;

import com.github.downgoon.jresty.rest.auto.naming.LayerNaming;
import com.github.downgoon.jresty.rest.auto.naming.NamingConvert;
import com.github.downgoon.jresty.rest.auto.naming.NamingRules;

public class CodeTemplateReplacer {
	
	/** model name (java pojo bean) in template code file edited by some person */
	protected String templateModelName;
	
	protected File templateFile;
	
	protected LayerNaming layerNaming = NamingRules.getLayerNaming();
	
	public CodeTemplateReplacer(File templateFile, String templateModelName) {
		super();
		this.templateFile = templateFile;
		this.templateModelName = templateModelName;
	}

	/*** 
	 * @param autogenModelName
	 * 			model name (java pojo bean) in autogen code file to be generated by this program 
	 * */
	public void replace(File autogenFile, String autogenModelName) throws IOException {
		BufferedReader tempReader = null;
		PrintWriter autoWriter = null;
		try {
			tempReader = new BufferedReader(new InputStreamReader(new FileInputStream(templateFile)));
			autoWriter = new PrintWriter(autogenFile);
			int lineNum = 1;
			String tempLine = tempReader.readLine();
			while (tempLine != null) {
				String autogenLine = replaceCodeLine(tempLine, lineNum, autogenModelName);
				autoWriter.println(autogenLine);
				lineNum ++;
				tempLine = tempReader.readLine();
			}
			autoWriter.flush();
			
		} finally {
			if (tempReader != null) {
				tempReader.close();
			}
			if (autoWriter != null) {
				autoWriter.close();
			}
		}
	}
	
	/**
	 * for action code, overwrite it for other code
	 * */
	protected String replaceCodeLine(final String tempLine, int lineNum, final String autogenModelName) {
		// replace type declare
		String autoLine = tempLine;
		autoLine = autoLine.replaceAll(templateModelName, autogenModelName);
		autoLine = autoLine.replaceAll(layerNaming.actionClass(templateModelName), layerNaming.actionClass(autogenModelName));
		autoLine = autoLine.replaceAll(layerNaming.daoIntfClass(templateModelName), layerNaming.daoIntfClass(autogenModelName));
		
		// replace var name
		String templateModelVar = NamingConvert.javaObjectName(templateModelName);
		String autogenModelVar = NamingConvert.javaObjectName(autogenModelName);
		autoLine = autoLine.replaceAll(templateModelVar, autogenModelVar);
		autoLine = autoLine.replaceAll(layerNaming.actionClass(templateModelVar), layerNaming.actionClass(autogenModelVar));
		autoLine = autoLine.replaceAll(layerNaming.daoIntfClass(templateModelVar), layerNaming.daoIntfClass(autogenModelVar));
		
		return autoLine;
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
		System.out.println("Begin");
		File tempFile = new File("/api/action/ApplicationAction.java");
		File autoFile = new File("/api/action/TopicsAction.java");
		
		CodeTemplateReplacer codeReplacer = new CodeTemplateReplacer(tempFile, "Application");
		codeReplacer.replace(autoFile, "Topics");
		System.out.println("End");
		
	}

}
